<?php

namespace common\models;

use Yii;
use yii\base\Model;

class CommentForm extends Model
{
    public string $comment = '';

    public function rules(): array
    {
        return [
            [['comment'], 'required' ],
            [['comment'], 'string', 'length' => [3,250]],
        ]; // TODO: Change the autogenerated stub
    }

    public function saveComment($article_id): bool
    {
        $comment = new Comment();
        $comment->text = $this->comment;
        $comment->user_id = Yii::$app->user->id;
        $comment->article_id = $article_id;
        $comment->status = 0;
        $comment->date = date('Y-m-d');
        return $comment->save();
    }
}